name: Build ESP32-S3 (Shibli Xiao Chatbot)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          version: v5.2.1   # Stable ESP-IDF version
          tools-cache: true

      - name: Configure ESP32-S3 target
        run: idf.py set-target esp32s3

      - name: Build firmware
        run: idf.py build
